import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';


const inter = Inter({ subsets: ['latin'] })
console.log(process.env.OPENAI_API);
export default function Home() {
  return (
    <>
      <Head>
        <title>SCORR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Screenshot 2023-01-16 at 23.51.40.png" />
      </Head>
      <main className={styles.main}>
          <h1 className={styles.center}>Welcome to SCORR</h1>
          <p><Link href="/Dealscoring">Deal Scoring</Link></p>
          <p><Link href="/funnel">Funnel </Link></p>        
          <p><Link href="/ProcessSetup">Set up </Link></p> 
                 
      </main>
    </>
  )
}
